# Generated by Django 4.2.20 on 2025-05-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_execucao',
            field=models.DateTimeField(),
        ),
    ]
