# Generated by Django 4.2.20 on 2025-05-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_data_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('executado', 'Executado pelo responsável'), ('validado', 'Validado pelo criador'), ('rejeitado', 'Rejeitado pelo criador')], default='pendente', max_length=20),
        ),
    ]
