# Generated by Django 4.2.20 on 2025-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_para_notificar',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
