# Generated by Django 4.2.20 on 2025-05-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'PENDENTE'), ('executado', 'EXECUTADO PELO RESPONSÁVEL'), ('validado', 'VALIDADO PELO RESPONSÁVEL'), ('rejeitado', 'REJEITADO PELO RESPONSÁVEL'), ('finalizado', 'FINALIZADO')], default='pendente', max_length=20),
        ),
    ]
