# Generated by Django 4.2.20 on 2025-05-03 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_user_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('numero_notas', models.CharField(blank=True, help_text='Separar por vírgulas se houver mais de uma nota', max_length=255)),
                ('codigo_barras', models.CharField(blank=True, max_length=255)),
                ('data_movimentacao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outros_acrescimos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcialmente Pago'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.filial')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.fornecedor')),
                ('tipo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.tipopagamento')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.transacao')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
