# Generated by Django 4.2.20 on 2025-05-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_empresa'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ['nome'], 'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='tipopagamento',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Pagamento', 'verbose_name_plural': 'Tipos de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['nome'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterUniqueTogether(
            name='filial',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='tipopagamento',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='transacao',
            unique_together={('empresa', 'nome')},
        ),
    ]
