# Generated by Django 4.2.20 on 2025-05-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_filial_options_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.fornecedor'),
        ),
    ]
