# Generated by Django 4.2.20 on 2025-05-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_contapagar_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
