# Generated by Django 4.2.20 on 2025-05-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_filial_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('a_vencer', 'À Vencer'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='a_vencer', max_length=20),
        ),
    ]
