# Generated by Django 4.2.20 on 2025-10-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_filial_conta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='conta_bancaria_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_banco_pagador', to='financeiro.filial', verbose_name='Conta Bancária para Pagamento'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_filial', to='financeiro.filial'),
        ),
    ]
