# Generated by Django 4.2.20 on 2025-10-21 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_user_tempo_antecedencia_minutos'),
        ('financeiro', '0008_contapagar_conta_bancaria_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFaturamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='Mês de referência (1-12)')),
                ('ano', models.IntegerField(help_text='Ano de referência')),
                ('arquivo_zip', models.FileField(blank=True, null=True, upload_to='relatorios_faturamento/%Y/%m/')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório de Faturamento Mensal',
                'verbose_name_plural': 'Relatórios de Faturamento Mensal',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('empresa', 'mes', 'ano')},
            },
        ),
    ]
