# Generated by Django 4.2.20 on 2025-10-21 17:13

from django.db import migrations, models
import financeiro.models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_relatoriofaturamentomensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriofaturamentomensal',
            name='arquivo_zip',
            field=models.FileField(blank=True, null=True, storage=financeiro.models.OverwriteStorage(), upload_to='relatorios_faturamento/%Y/%m/'),
        ),
    ]
