# Generated by Django 4.2.20 on 2025-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_alter_relatoriofaturamentomensal_arquivo_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='eh_recorrente',
            field=models.BooleanField(default=False, verbose_name='É recorrente?'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_parcela',
            field=models.IntegerField(blank=True, help_text='Número desta parcela (ex: 1 de 12)', null=True, verbose_name='Nº da Parcela'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='recorrencia_grupo',
            field=models.CharField(blank=True, help_text='Identificador do grupo de contas recorrentes', max_length=100, null=True, verbose_name='Grupo de recorrência'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='recorrencia_tipo',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal (7 dias)'), ('quinzenal', 'Quinzenal (15 dias)'), ('mensal', 'Mensal (1 mês)'), ('bimestral', 'Bimestral (2 meses)'), ('trimestral', 'Trimestral (3 meses)'), ('semestral', 'Semestral (6 meses)'), ('anual', 'Anual (12 meses)')], max_length=20, null=True, verbose_name='Tipo de recorrência'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='total_parcelas',
            field=models.IntegerField(blank=True, help_text='Total de parcelas da recorrência', null=True, verbose_name='Total de Parcelas'),
        ),
    ]
