# Generated by Django 4.2.20 on 2025-10-22 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_user_tempo_antecedencia_minutos'),
        ('financeiro', '0011_contapagar_eh_recorrente_contapagar_numero_parcela_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(help_text='Chave de 44 dígitos da NF-e', max_length=44, unique=True, verbose_name='Chave de Acesso')),
                ('numero', models.CharField(help_text='Número da nota fiscal', max_length=20, verbose_name='Número')),
                ('serie', models.CharField(blank=True, max_length=10, verbose_name='Série')),
                ('tipo_documento', models.CharField(choices=[('nfe', 'NF-e - Nota Fiscal Eletrônica'), ('cte', 'CT-e - Conhecimento de Transporte Eletrônico'), ('nfce', 'NFC-e - Nota Fiscal ao Consumidor Eletrônica')], default='nfe', max_length=10, verbose_name='Tipo')),
                ('data_emissao', models.DateTimeField(verbose_name='Data de Emissão')),
                ('data_entrada_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data Entrada/Saída')),
                ('emitente_cnpj', models.CharField(max_length=14, verbose_name='CNPJ Emitente')),
                ('emitente_nome', models.CharField(max_length=255, verbose_name='Razão Social Emitente')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Desconto')),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Líquido')),
                ('arquivo_xml', models.FileField(help_text='Arquivo XML da NF-e', upload_to='notas_fiscais/%Y/%m/')),
                ('nsu', models.CharField(blank=True, help_text='Número Sequencial Único da SEFAZ', max_length=15, verbose_name='NSU')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Análise'), ('vinculado', 'Vinculado a Conta'), ('importado', 'Importado como Conta'), ('descartado', 'Descartado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a nota')),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_pagar', models.ForeignKey(blank=True, help_text='Conta a Pagar vinculada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='financeiro.contapagar')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='accounts.empresa')),
                ('filial', models.ForeignKey(help_text='CNPJ destinatário da nota', on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='financeiro.filial')),
                ('importado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Fiscal Eletrônica',
                'verbose_name_plural': 'Notas Fiscais Eletrônicas',
                'ordering': ['-data_emissao'],
                'indexes': [models.Index(fields=['chave_acesso'], name='financeiro__chave_a_9c6f11_idx'), models.Index(fields=['emitente_cnpj'], name='financeiro__emitent_b32a0b_idx'), models.Index(fields=['data_emissao'], name='financeiro__data_em_b07d6f_idx'), models.Index(fields=['status'], name='financeiro__status_4532a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_pfx', models.FileField(help_text='Arquivo .pfx ou .p12 do certificado digital A1', upload_to='certificados/%Y/%m/')),
                ('senha_encrypted', models.BinaryField(help_text='Senha do certificado (criptografada automaticamente)')),
                ('uf_codigo', models.CharField(choices=[('11', 'Rondônia'), ('12', 'Acre'), ('13', 'Amazonas'), ('14', 'Roraima'), ('15', 'Pará'), ('16', 'Amapá'), ('17', 'Tocantins'), ('21', 'Maranhão'), ('22', 'Piauí'), ('23', 'Ceará'), ('24', 'Rio Grande do Norte'), ('25', 'Paraíba'), ('26', 'Pernambuco'), ('27', 'Alagoas'), ('28', 'Sergipe'), ('29', 'Bahia'), ('31', 'Minas Gerais'), ('32', 'Espírito Santo'), ('33', 'Rio de Janeiro'), ('35', 'São Paulo'), ('41', 'Paraná'), ('42', 'Santa Catarina'), ('43', 'Rio Grande do Sul'), ('50', 'Mato Grosso do Sul'), ('51', 'Mato Grosso'), ('52', 'Goiás'), ('53', 'Distrito Federal')], help_text='Estado para consulta na SEFAZ', max_length=2, verbose_name='UF')),
                ('data_validade', models.DateField(help_text='Data de vencimento do certificado')),
                ('ativo', models.BooleanField(default=True, help_text='Certificado ativo para uso')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultimo_nsu', models.CharField(default='000000000000000', help_text='Último NSU consultado na SEFAZ', max_length=15)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='accounts.empresa')),
                ('filial', models.ForeignKey(help_text='Filial proprietária do certificado (CNPJ)', on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='financeiro.filial')),
            ],
            options={
                'verbose_name': 'Certificado Digital',
                'verbose_name_plural': 'Certificados Digitais',
                'ordering': ['-ativo', 'filial__nome'],
                'unique_together': {('empresa', 'filial')},
            },
        ),
    ]
