# Generated by Django 4.2.20 on 2025-10-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_notafiscal_certificadodigital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoNFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busca_automatica_ativa', models.BooleanField(default=False, help_text='Se ativo, o sistema buscará novas notas automaticamente a cada 4 horas', verbose_name='Busca Automática Ativa')),
                ('busca_historica_ativa', models.BooleanField(default=False, help_text='Se ativo, o sistema buscará notas antigas de forma incremental', verbose_name='Busca Histórica Ativa')),
                ('busca_historica_status', models.CharField(choices=[('inativa', 'Inativa'), ('ativa', 'Ativa'), ('executando', 'Executando'), ('erro', 'Erro'), ('concluida', 'Concluída')], default='inativa', max_length=20, verbose_name='Status da Busca Histórica')),
                ('busca_historica_progresso', models.IntegerField(default=0, help_text='Percentual de conclusão da busca histórica', verbose_name='Progresso da Busca Histórica (%)')),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
                ('proximo_agendamento', models.DateTimeField(blank=True, null=True, verbose_name='Próximo Agendamento')),
                ('total_notas_importadas', models.IntegerField(default=0, help_text='Total de notas importadas desde a ativação', verbose_name='Total de Notas Importadas')),
                ('ultima_importacao_quantidade', models.IntegerField(default=0, help_text='Quantidade de notas importadas na última execução', verbose_name='Última Importação - Quantidade')),
                ('ultimo_erro', models.TextField(blank=True, verbose_name='Último Erro')),
                ('data_ultimo_erro', models.DateTimeField(blank=True, null=True, verbose_name='Data do Último Erro')),
                ('tentativas_erro', models.IntegerField(default=0, help_text='Contador de tentativas consecutivas com erro', verbose_name='Tentativas com Erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('certificado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_nfe', to='financeiro.certificadodigital', verbose_name='Certificado Digital')),
            ],
            options={
                'verbose_name': 'Configuração NFe',
                'verbose_name_plural': 'Configurações NFe',
                'db_table': 'configuracao_nfe',
            },
        ),
    ]
