# Generated by Django 4.2.20 on 2025-04-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa'),
            preserve_default=False,
        ),
    ]
