# Generated by Django 4.2.20 on 2025-05-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telefone_user_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nivel_acesso',
        ),
    ]
