# Generated by Django 4.2.20 on 2025-05-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_nivel_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receber_notificacoes_de_subordinados',
            field=models.BooleanField(default=False),
        ),
    ]
