# Generated by Django 4.2.20 on 2025-05-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_receber_notificacoes_de_subordinados'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tempo_antecedencia_minutos',
            field=models.PositiveIntegerField(default=90, help_text='Minutos de antecedência para notificação de tarefas.'),
        ),
    ]
